language: php

php:
  - '7.0'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - echo "{\"http-basic\":{\"repo.magento.com\":{\"username\":\"${MAGENTO_USERNAME}\",\"password\":\"${MAGENTO_PASSWORD}\"}}}" > auth.json
  - composer install --prefer-dist

script:
  - php vendor/bin/phpunit